trigger:
  branches:
    include:
      - main
pool: vikrantagent

stages:
- stage: Terraform
  displayName: "Terraform Infrastructure Deployment"

  jobs:
  - job: TerraformDeploy
    displayName: "Terraform Init Plan Apply"
    steps:
    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'vikrantscn'
        backendAzureRmResourceGroupName: 'RG-DEV'
        backendAzureRmStorageAccountName: 'vikrantstorage9987'
        backendAzureRmContainerName: 'pravinnekramvikram'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      displayName: "Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'vikrantscn'

    - task: TerraformTask@5
      displayName: "Terraform Apply"
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: 'vikrantscn'
        